Логинов Андрей
urfu-2018/markup-task-5 pull request #11
Opened 2018-11-07 09:41 UTC by AndrewLoginov

Решение(1)

2018-11-07 09:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 06:03 UTC, mokhov requested changes
1. В такой вёрстке (когда всегда есть хедер и футер) не принято чтобы был вертикальный скролл, когда всё влазит по высоте
2. Крестик, закрывающий попап при ховере становится не заметным (черным). Выглядит как баг

В остальном очень неплохо, но пока 🍅

2018-11-19 06:03 UTC, mokhov commented on index.css
> +    position: fixed;
Хорошо бы не использовать position: fixed

2018-11-19 08:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:29 UTC, closed without merging