Готов
urfu-2018/markup-task-5 pull request #19
Opened 2018-11-07 20:44 UTC by IIaKyJIuH

Но требует ещё доработки в классах css

2018-11-07 20:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-07 20:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 11:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 12:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 06:05 UTC, mokhov requested changes
1. При изменении высоты экрана футер наползает на котов
2. В попапе есть элементы, на которые можно навестись, но нельзя кликнуть
3. Затенение показывается поверх шапки, но не футера
4. Хорошо бы не портить пропорции картинок
🍅

2018-11-19 06:05 UTC, mokhov commented on index.css
> +    position: fixed;
Это можно сделать без position: fixed

2018-11-24 08:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-24 09:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:31 UTC, mokhov commented
Вот это
> Затенение показывается поверх шапки, но не футера
Не исправил

2018-12-30 09:59 UTC, closed without merging