Гридин Андрей
urfu-2018/markup-task-5 pull request #28
Opened 2018-11-08 02:46 UTC by Drusalyator

Просили написать про шапку из прошлого задания

2018-11-08 02:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-15 15:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-15 15:54 UTC, Drusalyator commented
Это случайно я последний commit кинул, не нужен он

2018-12-14 22:11 UTC, nex2hex requested changes
В шапке не хватает 
> Размер текста в шапке: 32px, шрифт: PT SansNarrow

Это на подключение шрифтов, лучше поправить

2018-12-14 22:11 UTC, nex2hex commented on index.html
> +            <div class="modal-window modal-cat-1">
каждое отдельное модальное окно можно обернуть в article

2018-12-15 12:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 12:50 UTC, Drusalyator commented
Исправил замечания

2019-01-12 05:07 UTC, closed without merging