Решение задачи Мурмаркет
urfu-2018/markup-task-5 pull request #30
Opened 2018-11-08 06:17 UTC by AIBarabanshchikova

2018-11-08 06:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 06:12 UTC, mokhov requested changes
Свёрстано аккуратно, это здорово, но нужно все-таки сделать без fixed'ов и так чтобы котики всегда были видны, даже на небольших экранах. И вот ещё что можно улучшить.
1. Можно добавить анимацию появления/исчезания котика
2. Затенение должно быть поверх всех элементов
🍅

2018-11-19 06:12 UTC, mokhov commented on index.css
> +    position: fixed;
Это можно сделать без position: fixed

2018-11-19 08:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 08:48 UTC, AIBarabanshchikova commented
🍏 
Всё поправила:  убрала position: fixed; теперь затеняется всё; анимацию тоже сделала)
+ работает на маленьких экранах

2018-12-03 05:29 UTC, mokhov commented
При ресайзе коты едут, это не ок конечно

2018-12-03 05:29 UTC, closed without merging