добавлена карусель
urfu-2018/markup-task-5 pull request #40
Opened 2018-11-08 10:36 UTC by sHooKDT

2018-11-08 10:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-11 12:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-12 06:07 UTC, Xrias requested changes

2018-11-12 06:07 UTC, Xrias commented on index.html
> +    <div class="carousel">
Давай добавим семантики

2018-11-16 04:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-16 04:13 UTC, sHooKDT commented on index.html
> +    <div class="carousel">
сделал списком, больше про семантику каруселей ничего не нашел

2018-11-16 04:13 UTC, sHooKDT commented
:green_apple:

2018-11-22 05:54 UTC, Xrias commented
Я имел ввиду article section и тд) Но ок:D

2018-11-22 05:54 UTC, closed without merging