Почти всё сделано
urfu-2018/markup-task-5 pull request #43
Opened 2018-11-08 11:13 UTC by Nerzull3

2018-11-08 11:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-11 16:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-11 16:16 UTC, Nerzull3 commented
Я очень много времени пытался избавиться от "мерцания" имени, но так и не смог :(
Модальное окно работает хорошо, просто нужно выследить момент, когда немного затемнятся бока картинки, и нажать. К сожалению, пока так. Не понимаю пока, в чём проблема

2018-11-26 20:10 UTC, spt30 requested changes
🍅Привет! Ты правильно заметил, что основная проблема – мерцание
Я описал ниже, как ее решить и в чем была проблема)
И еще несколько маленьких замечаний

По дедлайну сочтемся, я немного отстал и не проверял важные таски по модели отображения, поэтому получается, что недодал тебе знаний
Поэтому закрою без просрочки, если поправишь в течение недели)

2018-11-26 20:10 UTC, spt30 commented on index.html
> +        <header class="title"><h3>Мурмаркет</h3></header>
лучше 
```
<header class="title">
    <h3>Мурмаркет</h3>
</header>
```
для читабельности

2018-11-26 20:10 UTC, spt30 commented on index.html
> +            <ul class="carousel">
Респект за реализацию списком! 👍

2018-11-26 20:10 UTC, spt30 commented on index.html
> +                        <h3>Морис</h3>
![image](https://user-images.githubusercontent.com/31798669/49037997-7eaaf680-f1dd-11e8-870c-4b96adaa5cd3.png)

2018-11-26 20:10 UTC, spt30 commented on index.css
> +    cursor: pointer;
И еще один респект за   cursor: pointer, где надо! 👍

2018-11-26 20:10 UTC, spt30 commented on index.css
> +input[id='image-1']:checked ~ .carousel label[for$='1']:hover + .activated-cat,
Тут смотри какая петрушка получается:
структура
```
<li>
   <label/>
   <div/>
</li>
```

Ты пытаешься реагировать на ховер по лейблу
но когда ты на него наводишься, поскольку у тебя position absolute у дива стоит, он выходит поверх твоего лейбла, то есть на лейбл ты уже не наводишься
раз не наводишься, див исчезает и ты снова как будто бы наводишься на лейбл, но див снова встает поверх него и ты на лейбл уже не наводишься
из-за этого и мерцает и нельзя кликнуть

Чтобы такого не происходило, надо реагировать не на ховер лейбла, а на ховер `<li>`, тогда браузеру без разницы, что внутри li'шки как отображается, ты все равно наведен на нее

2018-11-26 20:10 UTC, spt30 commented on index.html
> +                        <label for="modal-input-1" class="close">&#9746;</label>
Семен Семёныч!
![image](https://user-images.githubusercontent.com/31798669/49039143-bebfa880-f1e0-11e8-98c8-cb56dc18be7c.png)
тут забыл cursor pointer))
и еще можно `user-select: none` добавлять, чтобы вот такого не было
![image](https://user-images.githubusercontent.com/31798669/49039179-dac34a00-f1e0-11e8-9d74-7c718f7babd9.png)

2018-11-26 20:12 UTC, spt30 commented
> Модальное окно работает хорошо, просто нужно выследить момент, когда немного затемнятся бока картинки, и нажать.
user-friendly интерфейс))

2018-11-26 20:18 UTC, spt30 commented
Слушай, еще было бы клево отступы у футера добавить, чтобы не прилипал

2018-11-26 20:33 UTC, Nerzull3 commented on index.html
> +                        <label for="modal-input-1" class="close">&#9746;</label>
да, как раз узнал недавно о такой фиче, как user-select. и использовал его в 4-м задании :)

2018-11-26 20:35 UTC, Nerzull3 commented on index.css
> +input[id='image-1']:checked ~ .carousel label[for$='1']:hover + .activated-cat,
А, вот оно что! Всё, вроде осознал. Переделаю

2018-11-26 20:44 UTC, spt30 commented
Все время что-то забываю в твоих задачках))
Если еще не начал править – хорошо бы как-то зафиксировать высоту карусели, чтобы нижняя панель навигации не плавала вверх-вниз при переключении котиков

2018-11-26 20:57 UTC, Nerzull3 commented
Окей, поправлю)

2018-11-27 11:56 UTC, Nerzull3 commented on index.html
> +                        <label for="modal-input-1" class="close">&#9746;</label>
такой вопрос ещё: как более грамотно избавляться от текстовых узлов? Нашел решение с написанием пустого комментария между двумя блоками, но это, как мне кажется, очень костыльно.
![default](https://user-images.githubusercontent.com/32774760/49080395-51a22680-f265-11e8-9719-089c49c1fe97.png)

2018-11-27 12:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-27 12:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-27 18:27 UTC, spt30 commented on index.html
> +                        <label for="modal-input-1" class="close">&#9746;</label>
Не могу понять в чем проблема, если честно)
Напиши поподробнее в лс

2018-11-27 18:28 UTC, spt30 commented
🍏 Молодец!

2018-11-27 18:28 UTC, closed without merging

2018-11-27 20:15 UTC, spt30 commented
2 персональных респекта в одном ПР, почему бы не добавить экстру