Рожков Максим
urfu-2018/markup-task-5 pull request #45
Opened 2018-11-08 11:19 UTC by MaximRhz

Слайдер

2018-11-08 11:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 01:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-11 01:55 UTC, MaximRhz commented
🔔

2018-11-11 01:55 UTC, MaximRhz commented
Закрой пожалуйста старые задания)

2018-11-11 23:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-11 23:06 UTC, MaximRhz commented
Нужна помощь с шапкой сайта и футером, задание position relative у .content ломает верстку при poput

2018-11-14 06:21 UTC, chrighter requested changes
🍅

2018-11-14 06:21 UTC, chrighter commented on index.css
> +    box-shadow: 0 0 3px 2px rgba(0, 0, 0, .16);
Давай именовать цвета единообразно

2018-11-14 06:21 UTC, chrighter commented on index.css
> +.popup
![image](https://user-images.githubusercontent.com/22082557/48463035-6e1d7800-e7fc-11e8-9979-1bf9495013a0.png)
При открытом модальном окне должно быть видно `header`
![image](https://user-images.githubusercontent.com/22082557/48463071-8e4d3700-e7fc-11e8-846d-073f89d78d26.png)

2018-11-14 06:21 UTC, chrighter commented on index.css
> +
Лишняя строка

2018-11-14 06:21 UTC, chrighter commented on index.css
> +.footer-right
Не может быть на странице левого и правого футера, футер всегда один
Давай назовем классы по контенту

2018-11-14 06:21 UTC, chrighter commented on index.html
> +            <div class="slider-container">
Давай семантику добавим

2018-11-14 06:21 UTC, chrighter commented on index.css
> +input
Лучше использовать более специфичный селектор, ведь если у тебя появятся инпуты на странице, придется переписывать CSS

2018-11-17 21:51 UTC, MaximRhz commented on index.css
> +    box-shadow: 0 0 3px 2px rgba(0, 0, 0, .16);
Зачем? Мне не нужно везде RGBA

2018-11-17 22:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 10:46 UTC, chrighter approved these changes
🍏

2018-12-05 10:47 UTC, closed without merging