Орлов Илья
urfu-2018/markup-task-5 pull request #49
Opened 2018-11-08 11:44 UTC by Orilow

Еще не все)

2018-11-08 11:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-09 09:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-09 19:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-09 19:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-09 21:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 21:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 21:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-11 11:13 UTC, Orilow commented
🔔

2018-11-12 14:34 UTC, Dotokoto commented
В целом очень хорошо! Но по условию задачи, фотографии должны листаться при нажатии на неактивную фотку. А у тебя сейчас открывается модалка

2018-11-12 14:35 UTC, Dotokoto commented
<img width="1440" alt="2018-11-12 19-35-35" src="https://user-images.githubusercontent.com/8973726/48353830-28ed2f00-e6b2-11e8-94de-76bbc85d3b40.png">
Текст не всегда влезает

2018-11-12 14:51 UTC, dotokoto requested changes

2018-11-12 14:51 UTC, Dotokoto commented on index.html
> +    <!-- <div class="header-wrapper"></div> -->
Лишнее? Лучше удалять все лишние комменты

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +    font-family: Arial, Helvetica, sans-serif;
Можно записать через одно свойство `font`

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +.float-right
Название запутывает, так как тут на самом деле не `float` ) Лучше бы переименовать

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +.footer-element-margin
Обычно не принято класс называть под правила, которые в нем. Так как стили со временем могут меняться. Можно переименовать в `footer-element` или как-нибудь так

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +    color: #4c4cd8;
Цвета не единообразно записаны. Где-то слова, где-то hex. Предлагаю везде использовать hex

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +    height: 12.5px;
Половинные пиксели будут правильно работать не на всех экранах. Лучше использовать целые значения

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +.footer > .footer-element-margin > img
А еще, поскольку это просто оформительская иконка, ее можно было сделать через `:before`

2018-11-12 14:51 UTC, Dotokoto commented on index.css
> +    background-position: center right;
Почему это свойство только у одной картинки? Оно точно нужно?

2018-11-14 06:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-14 06:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-14 06:09 UTC, Orilow commented
🔔  готово

2018-11-14 06:11 UTC, Orilow commented
Если не тяжело, то допроверьте, пожалуйста
https://github.com/urfu-2018/markup-task-3/pull/93
Я все исправил там

2018-11-14 08:28 UTC, dotokoto commented
<img width="1440" alt="2018-11-14 13-26-08" src="https://user-images.githubusercontent.com/8973726/48469553-00c81200-e811-11e8-91d2-670b05d3b85f.png">
Всё почти хорошо, только в футере теперь иконка "слиплась" с текстом и у бабушкиных котяток тоже иконка появилась, хотя она там не нужна

2018-11-14 08:28 UTC, dotokoto commented
Третью верстку закрыла

2018-11-14 16:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-14 16:19 UTC, Orilow commented
Все исправил.
А если вне задания уже говорить, то как мне можно улучшить мою карусель? 
Не в том плане, чтобы добавить что-либо существенно новое, а улучшить старое.
Может будут какие-то заметки у вас

2018-11-14 16:33 UTC, Orilow commented
И я тут посмотрел предыдущие закрытые пулы и увидел что мне не поставили `extra`. Это задание сдал вовремя и доп сделал
https://github.com/urfu-2018/markup-task-1/pull/41

2018-11-14 17:25 UTC, Orilow commented
Вспомнил вопрос: Когда подгружал шрифт с помощью `@font-face`, то шрифт, который я подгрузил по умолчанию был жирным, хотя я подгрузил обычную версию. Я сделал `font-weight: normal` и он стал нормальным. А разве так должно быть?

2018-11-15 13:46 UTC, Dotokoto commented on index.css
> +    font-style: bold;
Тут у тебя свойство перепутано.  У  `font-style` нет значения `bold`, оно есть у `font-weight`

2018-11-15 13:52 UTC, Dotokoto commented
1) Ну как вариант, добавить анимацию при наведении, чтобы затемнение происходило плавно 
2) Про шрифт так сходу непонятно. А какой именно из шрифтов, и где он становился жирным?

2018-11-16 05:40 UTC, Orilow commented
> 1. Ну как вариант, добавить анимацию при наведении, чтобы затемнение происходило плавно
> 2. Про шрифт так сходу непонятно. А какой именно из шрифтов, и где он становился жирным?

`PT Sans Narrow`. Если не указать `font-weight: normal`, то шрифт жирный(хотя скачал обычный).
Или я все-таки скачал криво?

2018-12-20 17:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-20 17:43 UTC, Orilow commented
В общем, о шрифте еще раз. Я взял обычный `PT Sans Narrow` ,а не жирный(в сети есть отдельно жирный). Однако, пока я не указал в классе .store-name `font-weight: normal`, он выводится жирным. 
Я пытался поставить это правило сразу в `@font-face`, но так почему-то не работало

2018-12-24 10:38 UTC, Dotokoto commented
Тьфу, шрифт то жирный становится из-за стандартных стилей заголовков. Так что всё нормально у тебя с его подключением

2018-12-24 10:39 UTC, closed without merging