Евдокимов Виктор
urfu-2018/markup-task-5 pull request #57
Opened 2018-11-08 12:27 UTC by VicClone

[Посмотреть решение](https://hruview.herokuapp.com/VicClone/markup-task-5/master/index.html)

2018-11-08 12:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-12 14:52 UTC, Dotokoto commented
У неактивных картинок по условию задачи должно стоять `opacity: 0.7`

2018-11-12 15:02 UTC, dotokoto requested changes

2018-11-12 15:02 UTC, dotokoto commented on font/PT_Sans_Narrow/OFL.txt
> +﻿Copyright (c) 2010, ParaType Ltd. (http://www.paratype.com/public),
Этот файл можно было не коммитить

2018-11-12 15:02 UTC, dotokoto commented on index.html
> +        <p>
Это скорее `div`, так как здесь не просто текст, а контейнер для ссылок

2018-11-12 15:02 UTC, dotokoto commented on index.html
> +            <br><a href="#">vnuchek@babuli.ru</a>
Не стоит использовать `br` для переносов, лучше сделать это через css

2018-11-12 15:02 UTC, dotokoto commented on index.css
> +    margin-right: auto;
Можно одним свойством: `margin: 0 auto;`

2018-11-12 15:02 UTC, Dotokoto commented on index.css
> +    line-height: 200px;
Большинство этих свойств не зависят от того, открыта модалка или нет. Можно дать этому `span` класс и определить свойства конкретно для него

2018-11-12 15:02 UTC, Dotokoto commented on index.css
> +    display: block;
`content: ''` тоже можно сюда унести

2018-11-12 15:02 UTC, Dotokoto commented on index.css
> +    font-size: 14px;
все стили для текста можно собрать в одно свойство `font`

2018-11-14 17:55 UTC, VicClone commented on index.css
> +    line-height: 200px;
Это же не для модалки, а изменение имени при наведении на блок слайдера

2018-11-14 18:02 UTC, VicClone commented on index.html
> +        <p>
Поменял p на div

2018-11-14 18:02 UTC, VicClone commented on index.html
> +            <br><a href="#">vnuchek@babuli.ru</a>
Задал ссылкам display: block;

2018-11-14 18:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-14 18:03 UTC, VicClone commented on index.css
> +    margin-right: auto;
Исправил

2018-11-14 18:03 UTC, VicClone commented on index.css
> +    display: block;
Объединил

2018-11-14 18:04 UTC, VicClone commented on index.css
> +    font-size: 14px;
Написал сокращенное свойство font

2018-11-15 13:41 UTC, Dotokoto commented
Принято

2018-11-15 13:41 UTC, closed without merging