Чусовитин Вячеслав
urfu-2018/markup-task-5 pull request #65
Opened 2018-11-08 13:08 UTC by VA-Chusovitin

2018-11-08 13:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 13:19 UTC, VA-Chusovitin commented
🔔 
У меня возникла проблема с модальными окнами. Модальное окно нормально открывается на второй картинки, а на остальных почему-то открывается не так. Можете подсказать из-за чего это?

2018-11-19 06:13 UTC, mokhov commented
Не понял что имеется ввиду, напиши в телеграм

2018-11-19 06:15 UTC, mokhov commented
Хотя если я верно понял, то проблема в слоях (т.е что над чем показывается). Если посмотреть через инспектор, то ссылка на которую ты пытаешься навеситься, ниже того что мы видим и по чему кликаем

2018-11-19 06:16 UTC, mokhov requested changes
1. Контент должен отодвигать футер вниз, когда не влазит по высоте
2. Пропорции котиков хорошо бы не портить
🍅

2018-11-19 06:16 UTC, mokhov commented on index.css
> +    position: fixed;
Это можно сделать без position: fixed

2019-01-11 09:24 UTC, closed without merging