me
urfu-2018/markup-task-5 pull request #9
Opened 2018-11-06 12:19 UTC by zarix908

2018-11-06 12:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-06 15:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-08 11:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-08 12:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 05:57 UTC, mokhov requested changes
Очень много проблем:
1. При уменьшении окна по вертикали футер наползает на фоточки.
2. При наведении на фоточку все остальные прыгают
3. При клике ничего не происходит (браузер Firefox)
4. Котиков хорошо бы уменьшать пропорционально, а не портить размеры

🍅

2018-11-19 05:57 UTC, mokhov commented on index.css
> +    position: fixed;
У position: fixed есть недостатки. Сможешь переделать шапку без position: fixed?

2019-01-11 09:19 UTC, closed without merging